### PR TITLE
Add middleware-labs to the extensions list

### PR DESCRIPTION
**Pull request by savan-kharod**
Please add Middleware to the list. :)

### CODE REVIEW

**Comment by felipecruz91** [comment]
Hi @savan-kharod, thanks for your contribution. It seems that your extension is the result of having run docker extension init. In order to consider your Docker Extension to be added to the list, we'd like to know what user pain point solves.

**Comment by savan-kharod** [comment]
Hi @felipecruz91, I added this contribution after having a word with Ajeet. My team and I are working on creating the extension. It should be up by the end of next week. 

We are a full-stack observability platform, and this extension will be collecting container stats -- Ex. container network usage, disk usage, etc. 

The plus point of using our extension is data retention; we can store this data history in clickhouse, so the client can go back in time and see what was the statistics at a particular time.

Let me know if I can give you more context about our tool/use cases/pain points.

**Comment by gtardif** [comment]
Hi @savan-kharod, Thx for your contribution. While working on the extension, don't hesitate to provide a detailed description of what you plan to build as an extension in your repo's README, we could merge the addition of this in the list even if the extension is not fully implemented, as long as we have a good description of what developer pain it solves.

**Comment by savan-kharod** [comment]
Hey @gtardif, we updated the README in our repo: https://github.com/middleware-labs/middleware-docker-extension. :)

**Review by gtardif — APPROVED** [review]

**Pull request merged**
